import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/src/components/ui/sonner";
import Link from "next/link";
import {SessionProvider} from "next-auth/react";
import {Button} from "@/src/components/ui/button";
import {auth, signOut} from "@/auth";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await auth();
    console.log(session)
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <SessionProvider>
            <nav>
                <Link href="/sign-in">
                    Sign In
                </Link>
                <Link href="/sign-up">
                    Sign Up
                </Link>
                {
                    session && (
                        <form action={
                            async () => {
                                "use server"
                                await signOut();
                            }
                        }>
                            <Button type="submit">
                                Sign Out
                            </Button>
                        </form>
                    )
                }
            </nav>
            {children}
            <Toaster/>
        </SessionProvider>
        </body>
        </html>
    );
}
